// Error taxonomy per Part 3.0 §6. Add codes here as new endpoints need them.

export const ErrorCode = {
  // Auth
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_IDENTITY_NOT_PROVISIONED: 'AUTH_IDENTITY_NOT_PROVISIONED',

  // Identity
  IDENTITY_PHONE_TAKEN: 'IDENTITY_PHONE_TAKEN',
  IDENTITY_PHONE_CLAIM_MISSING: 'IDENTITY_PHONE_CLAIM_MISSING',
  IDENTITY_NOT_CUSTOMER: 'IDENTITY_NOT_CUSTOMER',
  IDENTITY_HAS_ACTIVE_BOOKINGS: 'IDENTITY_HAS_ACTIVE_BOOKINGS',
  IDENTITY_NOT_FOUND: 'IDENTITY_NOT_FOUND',
  DEVICE_ID_MISMATCH: 'DEVICE_ID_MISMATCH',
  DEVICE_TOKEN_NOT_FOUND: 'DEVICE_TOKEN_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  UPLOAD_INVALID: 'UPLOAD_INVALID',
  UPLOAD_NOT_AUTHORISED: 'UPLOAD_NOT_AUTHORISED',
  UPLOAD_UNSUPPORTED_CONTENT_TYPE: 'UPLOAD_UNSUPPORTED_CONTENT_TYPE',
  UPLOAD_SIZE_LIMIT_EXCEEDED: 'UPLOAD_SIZE_LIMIT_EXCEEDED',
  UPLOAD_PROVIDER_ERROR: 'UPLOAD_PROVIDER_ERROR',
  AVAILABILITY_INVALID_DATE: 'AVAILABILITY_INVALID_DATE',

  // Partner
  PARTNER_NOT_VERIFIED: 'PARTNER_NOT_VERIFIED',
  PARTNER_NOT_FOUND: 'PARTNER_NOT_FOUND',
  PARTNER_ALREADY_EXISTS: 'PARTNER_ALREADY_EXISTS',
  PARTNER_INVALID_CITY: 'PARTNER_INVALID_CITY',
  PARTNER_SUBMIT_PRECONDITIONS: 'PARTNER_SUBMIT_PRECONDITIONS',
  IDENTITY_VERIFICATION_INCOMPLETE: 'IDENTITY_VERIFICATION_INCOMPLETE',

  // Venue
  VENUE_NOT_PUBLISHED: 'VENUE_NOT_PUBLISHED',
  VENUE_ALREADY_PUBLISHED: 'VENUE_ALREADY_PUBLISHED',
  VENUE_NO_ACTIVE_GROUND: 'VENUE_NO_ACTIVE_GROUND',
  VENUE_SLUG_TAKEN: 'VENUE_SLUG_TAKEN',
  VENUE_OUTSIDE_NASHIK: 'VENUE_OUTSIDE_NASHIK',
  VENUE_NOT_FOUND: 'VENUE_NOT_FOUND',
  VENUE_LOCATION_OUT_OF_SCOPE: 'VENUE_LOCATION_OUT_OF_SCOPE',
  VENUE_INVALID_AMENITY: 'VENUE_INVALID_AMENITY',
  VENUE_STATUS_LOCKED: 'VENUE_STATUS_LOCKED',
  VENUE_MEDIA_NOT_FOUND: 'VENUE_MEDIA_NOT_FOUND',

  // Ground
  GROUND_NOT_ACTIVE: 'GROUND_NOT_ACTIVE',
  GROUND_CONFIG_MISSING: 'GROUND_CONFIG_MISSING',
  GROUND_NO_ACTIVE_PRICING: 'GROUND_NO_ACTIVE_PRICING',
  GROUND_NOT_FOUND: 'GROUND_NOT_FOUND',
  GROUND_STATE_TRANSITION_INVALID: 'GROUND_STATE_TRANSITION_INVALID',
  GROUND_MEDIA_NOT_FOUND: 'GROUND_MEDIA_NOT_FOUND',
  GROUND_CONFIG_INVALID: 'GROUND_CONFIG_INVALID',
  SPORT_NOT_FOUND: 'SPORT_NOT_FOUND',

  // Scheduling
  EXCEPTION_CONFLICTS_BOOKING: 'EXCEPTION_CONFLICTS_BOOKING',
  MAINTENANCE_CONFLICTS_BOOKING: 'MAINTENANCE_CONFLICTS_BOOKING',
  EXCEPTION_NOT_FOUND: 'EXCEPTION_NOT_FOUND',
  MAINTENANCE_BLOCK_NOT_FOUND: 'MAINTENANCE_BLOCK_NOT_FOUND',
  OPERATING_HOURS_INVALID: 'OPERATING_HOURS_INVALID',

  // Pricing
  PRICING_PRIORITY_TAKEN: 'PRICING_PRIORITY_TAKEN',
  PRICING_RULE_NOT_FOUND: 'PRICING_RULE_NOT_FOUND',
  PRICING_INVALID: 'PRICING_INVALID',

  // Availability
  AVAILABILITY_NO_OPERATING_HOURS: 'AVAILABILITY_NO_OPERATING_HOURS',
  AVAILABILITY_OUTSIDE_WINDOW: 'AVAILABILITY_OUTSIDE_WINDOW',

  // Booking
  BOOKING_SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_SESSION_EXPIRED: 'BOOKING_SESSION_EXPIRED',
  BOOKING_SESSION_NOT_FOUND: 'BOOKING_SESSION_NOT_FOUND',
  BOOKING_ALREADY_CONFIRMED: 'BOOKING_ALREADY_CONFIRMED',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_CANCELLATION_WINDOW: 'BOOKING_CANCELLATION_WINDOW',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',
  BOOKING_ADVANCE_WINDOW: 'BOOKING_ADVANCE_WINDOW',
  BOOKING_MIN_NOTICE: 'BOOKING_MIN_NOTICE',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',

  // Payment
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  REFUND_INELIGIBLE: 'REFUND_INELIGIBLE',

  // Idempotency
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  IDEMPOTENCY_KEY_IN_FLIGHT: 'IDEMPOTENCY_KEY_IN_FLIGHT',

  // Cross-cutting
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_STALE: 'RESOURCE_STALE',
  SYSTEM_DEPENDENCY_UNAVAILABLE: 'SYSTEM_DEPENDENCY_UNAVAILABLE',
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
} as const;

export type ErrorCodeKey = keyof typeof ErrorCode;

// Maps each code to the HTTP status it MUST return (Part 3.0 §5–§6).
// If a code isn't listed, DomainException.statusCode defaults to 400.
export const ERROR_STATUS: Record<ErrorCodeKey, number> = {
  AUTH_TOKEN_MISSING: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_IDENTITY_NOT_PROVISIONED: 401,
  AUTH_INSUFFICIENT_PERMISSIONS: 403,
  AUTH_ACCOUNT_SUSPENDED: 403,

  IDENTITY_PHONE_TAKEN: 409,
  IDENTITY_PHONE_CLAIM_MISSING: 400,
  IDENTITY_NOT_CUSTOMER: 404,
  IDENTITY_HAS_ACTIVE_BOOKINGS: 409,
  IDENTITY_NOT_FOUND: 404,
  DEVICE_ID_MISMATCH: 409,
  DEVICE_TOKEN_NOT_FOUND: 404,
  NOTIFICATION_NOT_FOUND: 404,
  UPLOAD_INVALID: 400,
  UPLOAD_NOT_AUTHORISED: 403,
  UPLOAD_UNSUPPORTED_CONTENT_TYPE: 400,
  UPLOAD_SIZE_LIMIT_EXCEEDED: 400,
  UPLOAD_PROVIDER_ERROR: 503,
  AVAILABILITY_INVALID_DATE: 400,

  PARTNER_NOT_VERIFIED: 403,
  PARTNER_NOT_FOUND: 404,
  PARTNER_ALREADY_EXISTS: 409,
  PARTNER_INVALID_CITY: 400,
  PARTNER_SUBMIT_PRECONDITIONS: 409,
  IDENTITY_VERIFICATION_INCOMPLETE: 403,

  VENUE_NOT_PUBLISHED: 403,
  VENUE_ALREADY_PUBLISHED: 409,
  VENUE_NO_ACTIVE_GROUND: 409,
  VENUE_SLUG_TAKEN: 409,
  VENUE_OUTSIDE_NASHIK: 409,
  VENUE_NOT_FOUND: 404,
  VENUE_LOCATION_OUT_OF_SCOPE: 400,
  VENUE_INVALID_AMENITY: 400,
  VENUE_STATUS_LOCKED: 409,
  VENUE_MEDIA_NOT_FOUND: 404,

  GROUND_NOT_ACTIVE: 403,
  GROUND_CONFIG_MISSING: 409,
  GROUND_NO_ACTIVE_PRICING: 409,
  GROUND_NOT_FOUND: 404,
  GROUND_STATE_TRANSITION_INVALID: 409,
  GROUND_MEDIA_NOT_FOUND: 404,
  GROUND_CONFIG_INVALID: 400,
  SPORT_NOT_FOUND: 404,

  EXCEPTION_CONFLICTS_BOOKING: 409,
  MAINTENANCE_CONFLICTS_BOOKING: 409,
  EXCEPTION_NOT_FOUND: 404,
  MAINTENANCE_BLOCK_NOT_FOUND: 404,
  OPERATING_HOURS_INVALID: 400,

  PRICING_PRIORITY_TAKEN: 409,
  PRICING_RULE_NOT_FOUND: 404,
  PRICING_INVALID: 400,

  AVAILABILITY_NO_OPERATING_HOURS: 409,
  AVAILABILITY_OUTSIDE_WINDOW: 409,

  BOOKING_SLOT_UNAVAILABLE: 409,
  BOOKING_SESSION_EXPIRED: 410,
  BOOKING_SESSION_NOT_FOUND: 404,
  BOOKING_ALREADY_CONFIRMED: 409,
  BOOKING_ALREADY_CANCELLED: 409,
  BOOKING_CANCELLATION_WINDOW: 409,
  BOOKING_NOT_CANCELLABLE: 409,
  BOOKING_ADVANCE_WINDOW: 409,
  BOOKING_MIN_NOTICE: 409,
  BOOKING_NOT_FOUND: 404,

  PAYMENT_ALREADY_CAPTURED: 409,
  PAYMENT_SIGNATURE_INVALID: 400,
  PAYMENT_AMOUNT_MISMATCH: 409,
  PAYMENT_PROVIDER_ERROR: 503,
  REFUND_INELIGIBLE: 409,

  IDEMPOTENCY_KEY_CONFLICT: 409,
  IDEMPOTENCY_KEY_IN_FLIGHT: 409,

  VALIDATION_FAILED: 400,
  RATE_LIMIT_EXCEEDED: 429,
  RESOURCE_NOT_FOUND: 404,
  RESOURCE_STALE: 409,
  SYSTEM_DEPENDENCY_UNAVAILABLE: 503,
  SYSTEM_INTERNAL_ERROR: 500,
};

// Default human-readable message per code. Callers may override at throw-site.
export const ERROR_MESSAGE: Record<ErrorCodeKey, string> = {
  AUTH_TOKEN_MISSING: 'Authentication token is required.',
  AUTH_TOKEN_INVALID: 'Authentication token is invalid.',
  AUTH_TOKEN_EXPIRED: 'Authentication token has expired.',
  AUTH_IDENTITY_NOT_PROVISIONED: 'Identity has not been provisioned; call /auth/session first.',
  AUTH_INSUFFICIENT_PERMISSIONS: 'You do not have permission to perform this action.',
  AUTH_ACCOUNT_SUSPENDED: 'This account is suspended.',

  IDENTITY_PHONE_TAKEN: 'This phone number is already used by another account.',
  IDENTITY_PHONE_CLAIM_MISSING: 'Firebase token does not contain a verified phone number.',
  IDENTITY_NOT_CUSTOMER: 'Customer reference codes are only available to customer identities.',
  IDENTITY_HAS_ACTIVE_BOOKINGS: 'Account has confirmed future bookings; cancel them before deletion.',
  IDENTITY_NOT_FOUND: 'Identity not found.',
  DEVICE_ID_MISMATCH: 'Body device_id does not match the X-Device-Id header.',
  DEVICE_TOKEN_NOT_FOUND: 'Device token not found.',
  NOTIFICATION_NOT_FOUND: 'Notification not found.',
  UPLOAD_INVALID: 'The upload URL is invalid or unreachable.',
  UPLOAD_NOT_AUTHORISED: 'You are not authorised to upload to this target.',
  UPLOAD_UNSUPPORTED_CONTENT_TYPE: 'Content-type is not in the allow-list.',
  UPLOAD_SIZE_LIMIT_EXCEEDED: 'Upload exceeds the maximum size.',
  UPLOAD_PROVIDER_ERROR: 'Upload provider returned an error.',
  AVAILABILITY_INVALID_DATE: 'Date must be in YYYY-MM-DD format.',

  PARTNER_NOT_VERIFIED: 'Partner is not verified.',
  PARTNER_NOT_FOUND: 'Partner not found.',
  PARTNER_ALREADY_EXISTS: 'This account already owns a partner.',
  PARTNER_INVALID_CITY: 'Partner city must be Nashik for MVP.',
  PARTNER_SUBMIT_PRECONDITIONS: 'Partner cannot be submitted for review yet; check the verification checklist.',
  IDENTITY_VERIFICATION_INCOMPLETE: 'Email and phone must be verified before this action.',

  VENUE_NOT_PUBLISHED: 'Venue is not published.',
  VENUE_ALREADY_PUBLISHED: 'Venue is already published.',
  VENUE_NO_ACTIVE_GROUND: 'Venue must have at least one active ground before publishing.',
  VENUE_SLUG_TAKEN: 'This venue slug is already taken.',
  VENUE_OUTSIDE_NASHIK: 'Venue coordinates are outside the Nashik service area.',
  VENUE_NOT_FOUND: 'Venue not found.',
  VENUE_LOCATION_OUT_OF_SCOPE: 'Venue coordinates fall outside the Nashik bounding box.',
  VENUE_INVALID_AMENITY: 'One or more amenities are not supported.',
  VENUE_STATUS_LOCKED: 'This field cannot be changed after the venue leaves DRAFT.',
  VENUE_MEDIA_NOT_FOUND: 'Venue media not found.',

  GROUND_NOT_ACTIVE: 'Ground is not active.',
  GROUND_CONFIG_MISSING: 'Ground configuration is required.',
  GROUND_NO_ACTIVE_PRICING: 'Ground has no active pricing rule.',
  GROUND_NOT_FOUND: 'Ground not found.',
  GROUND_STATE_TRANSITION_INVALID: 'Ground cannot transition to that state from its current status.',
  GROUND_MEDIA_NOT_FOUND: 'Ground media not found.',
  GROUND_CONFIG_INVALID: 'Ground configuration failed validation.',
  SPORT_NOT_FOUND: 'Sport not found.',

  EXCEPTION_CONFLICTS_BOOKING: 'This exception overlaps an existing booking.',
  MAINTENANCE_CONFLICTS_BOOKING: 'Maintenance overlaps existing bookings.',
  EXCEPTION_NOT_FOUND: 'Availability exception not found.',
  MAINTENANCE_BLOCK_NOT_FOUND: 'Maintenance block not found.',
  OPERATING_HOURS_INVALID: 'Operating hours failed validation.',

  PRICING_PRIORITY_TAKEN: 'A pricing rule with this priority already exists.',
  PRICING_RULE_NOT_FOUND: 'Pricing rule not found.',
  PRICING_INVALID: 'Pricing rule failed validation.',

  AVAILABILITY_NO_OPERATING_HOURS: 'No operating hours configured for this day.',
  AVAILABILITY_OUTSIDE_WINDOW: 'Requested slot is outside the booking window.',

  BOOKING_SLOT_UNAVAILABLE: 'The requested slot is no longer available.',
  BOOKING_SESSION_EXPIRED: 'This booking session has expired.',
  BOOKING_SESSION_NOT_FOUND: 'Booking session not found.',
  BOOKING_ALREADY_CONFIRMED: 'Booking has already been confirmed.',
  BOOKING_ALREADY_CANCELLED: 'Booking has already been cancelled.',
  BOOKING_CANCELLATION_WINDOW: 'Cancellation is not allowed inside the notice window.',
  BOOKING_NOT_CANCELLABLE: 'Booking cannot be cancelled in its current state.',
  BOOKING_ADVANCE_WINDOW: 'Booking is beyond the allowed advance window.',
  BOOKING_MIN_NOTICE: 'Booking does not meet the minimum notice window.',
  BOOKING_NOT_FOUND: 'Booking not found.',

  PAYMENT_ALREADY_CAPTURED: 'Payment has already been captured.',
  PAYMENT_SIGNATURE_INVALID: 'Payment signature is invalid.',
  PAYMENT_AMOUNT_MISMATCH: 'Payment amount does not match the booking total.',
  PAYMENT_PROVIDER_ERROR: 'Payment provider returned an error.',
  REFUND_INELIGIBLE: 'This booking is not eligible for a refund.',

  IDEMPOTENCY_KEY_CONFLICT: 'Idempotency key was reused with a different request body.',
  IDEMPOTENCY_KEY_IN_FLIGHT: 'A request with this idempotency key is already in flight.',

  VALIDATION_FAILED: 'One or more fields failed validation.',
  RATE_LIMIT_EXCEEDED: 'Rate limit exceeded. Please retry later.',
  RESOURCE_NOT_FOUND: 'Requested resource was not found.',
  RESOURCE_STALE: 'This resource has been updated since you last read it.',
  SYSTEM_DEPENDENCY_UNAVAILABLE: 'A required upstream service is unavailable.',
  SYSTEM_INTERNAL_ERROR: 'Internal server error.',
};
