-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";

-- Business enums (Part 2.5.2 §3)
CREATE TYPE "Role" AS ENUM ('CUSTOMER', 'PARTNER', 'MANAGER', 'STAFF', 'ADMIN');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'INACTIVE', 'DELETED');
CREATE TYPE "PartnerStatus" AS ENUM ('PENDING', 'UNDER_REVIEW', 'ACTIVE', 'SUSPENDED', 'ARCHIVED');
CREATE TYPE "VenueStatus" AS ENUM ('DRAFT', 'UNDER_REVIEW', 'PUBLISHED', 'SUSPENDED', 'ARCHIVED');
CREATE TYPE "GroundStatus" AS ENUM ('DRAFT', 'ACTIVE', 'MAINTENANCE', 'BLOCKED', 'ARCHIVED');
CREATE TYPE "SurfaceType" AS ENUM ('NATURAL_GRASS', 'ARTIFICIAL_TURF', 'SYNTHETIC', 'CLAY', 'WOOD', 'RUBBER', 'CONCRETE');
CREATE TYPE "MediaType" AS ENUM ('COVER', 'GALLERY', 'LOGO');
CREATE TYPE "BookingSessionStatus" AS ENUM ('ACTIVE', 'EXPIRED', 'CANCELLED');
CREATE TYPE "BookingSource" AS ENUM ('CUSTOMER_APP', 'PARTNER_APP', 'WALK_IN', 'PHONE', 'WHATSAPP', 'ADMIN');
CREATE TYPE "BookingStatus" AS ENUM ('CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'NO_SHOW');
CREATE TYPE "PaymentProvider" AS ENUM ('RAZORPAY', 'OFFLINE');
CREATE TYPE "PaymentMethod" AS ENUM ('UPI', 'CARD', 'NETBANKING', 'CASH', 'WALLET');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED');

-- Platform enums (Part 2.5.3)
CREATE TYPE "OutboxStatus" AS ENUM ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED');
CREATE TYPE "NotificationChannel" AS ENUM ('PUSH', 'SMS', 'EMAIL', 'WHATSAPP', 'IN_APP');
CREATE TYPE "NotificationCategory" AS ENUM (
  'BOOKING_CONFIRMATION', 'BOOKING_REMINDER', 'BOOKING_CANCELLATION',
  'PAYMENT_SUCCESS', 'PAYMENT_FAILURE', 'REFUND_PROCESSED',
  'CHECK_IN_REMINDER', 'REVIEW_REQUEST', 'VENUE_APPROVED', 'VENUE_SUSPENDED',
  'GROUND_MAINTENANCE', 'PROMOTION', 'SYSTEM_ANNOUNCEMENT'
);
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED');
CREATE TYPE "DevicePlatform" AS ENUM ('ANDROID', 'IOS', 'WEB');
CREATE TYPE "AppVariant" AS ENUM ('CUSTOMER', 'PARTNER', 'ADMIN');
CREATE TYPE "AppSettingType" AS ENUM ('STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'SECRET');
CREATE TYPE "BackgroundJobType" AS ENUM ('SCHEDULED', 'ONE_SHOT');
CREATE TYPE "BackgroundJobStatus" AS ENUM ('IDLE', 'RUNNING', 'SUCCESS', 'FAILED', 'DISABLED');
